### ISSUE TITLE
Function add_contact has 42 lines of code (exceeds 25 allowed). 

### ISSUE THREAD

**Issue by eclacfo** [gahan-corporation/rsum.application#164]
Function `add_experience` has a Cognitive Complexity of 12 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/executive-consultants-of-los-angeles/rsum/files/rsum/rsum/home/export/word.py#issue_5a23cbd8b774cd00010000a0

**Comment by gahancorpcfo** [comment]
<img width="801" alt="screen shot 2018-01-12 at 5 02 48 am" src="https://user-images.githubusercontent.com/9362301/34876326-e26a293a-f755-11e7-993d-e440ad72a4d6.png">
